# Generated by Django 5.0.6 on 2024-07-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
